apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: project
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer